#534  Numpy related examples - collected by Satya

In [12]:
xTr = np.array([[1, 1 ,1],
 [1, 1, 0],
 [1, 0, 1],
 [1, 0, 0],
 [0, 1, 1],
 [0, 1, 0],
 [0 ,0, 1],
 [0, 0 ,0]])
yTr = np.array( [1, 0, 0, 1, 0, 1, 1, 0])
print('xTr',xTr)
print('xTr.shape',xTr.shape)
print('yTr',yTr)

'''
Specific column from xTr
xTr first column  [1 1 1 1 0 0 0 0]
 xTr second column  [1 1 0 0 1 1 0 0]
 xTr third column  [1 0 1 0 1 0 1 0]
''' 
print (" xTr first column ", xTr[:,0])
print (" xTr second column ", xTr[:,1])
print (" xTr third column ", xTr[:,2])

'''
Specific column -arg sorted from xTr
xTr first column -SORTED indices  [4 5 6 7 0 1 2 3]
 xTr first column -SORTED values  [0 0 0 0 1 1 1 1]
''' 
x1 = xTr[:,0].argsort()
print (" xTr first column -SORTED indices ", x1)

'''
using the first column sorted values to get xTr first column and corresponding yTr values
xTr first column -SORTED values  [0 0 0 0 1 1 1 1]
 yTr SORTED values based on col1 sorted indices [0 1 1 0 1 0 0 1]
''' 
col1x = xTr[x1, 0]  
col1y = yTr[x1]
print (" xTr first column -SORTED values ", col1x)
print (" yTr SORTED values based on col1 sorted indices", col1y)

'''
Break col1x into two parts at any index-  
''' 

print (" number of values in col1x ", col1x.size)
## what are the indexes then ?  starts from 0 to ??

## pick 4 as the index you want to break it
print (" part1  ", col1x[:3])
print (" part2  ", col1x[3:7])

'''
use the broken col1x indices and find out corresponding coly values

'''



'''
FOR loop example
i is 0
i is 1
i is 2
i is 3
i is 4
i is 5
i is 6
i is 7
i is 8
i is 9
'''
for i in range(10):
    print ("i is",i)

'''
FOR loop example with doing some operations in a loop
'''
testval = np.array( [1, 0, 2, 1, 5, 1, 1, 0])
for i in range(8):
    print ("i is",i) 
    print ("product of testval and i  is",i*testval[i]) 
    
    
'''
FOR loop example with finding what is the highest product
'''
testval1 = np.array( [1, 0, 2, 1, 5, 1, 1, 0])

besti = 0
bestproduct=0

for i in range(8):
    print ("i is",i) 
    print ("product of testval and i  is",i*testval[i]) 
    if (i*testval[i]) > bestproduct:
        besti = i
        bestproduct = (i*testval[i])
print(" best i and product are ", besti , bestproduct) 



'''
FOR loop example with finding what is the highest product by adding i and product to arrays
'''
testval1 = np.array( [1, 0, 2, 1, 5, 1, 1, 0])

allis = []
allproducts=[]

for i in range(8):
    print ("i is",i) 
    print ("product of testval and i  is",i*testval[i]) 
    allis.append(i) 
    allproducts.append(i*testval[i])

print("highest product is --->",np.argmax(allproducts))
print(" best i and product are ---> ", allis[np.argmax(allproducts)] , allproducts[np.argmax(allproducts)]) 

### recursive product example



xTr [[1 1 1]
 [1 1 0]
 [1 0 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 0 1]
 [0 0 0]]
xTr.shape (8, 3)
yTr [1 0 0 1 0 1 1 0]
 xTr first column  [1 1 1 1 0 0 0 0]
 xTr second column  [1 1 0 0 1 1 0 0]
 xTr third column  [1 0 1 0 1 0 1 0]
 xTr first column -SORTED indices  [4 5 6 7 0 1 2 3]
 xTr first column -SORTED values  [0 0 0 0 1 1 1 1]
 yTr SORTED values based on col1 sorted indices [0 1 1 0 1 0 0 1]
 number of values in col1x  8
 part1   [0 0 0]
 part2   [0 1 1 1]
i is 0
i is 1
i is 2
i is 3
i is 4
i is 5
i is 6
i is 7
i is 8
i is 9
i is 0
product of testval and i  is 0
i is 1
product of testval and i  is 0
i is 2
product of testval and i  is 4
i is 3
product of testval and i  is 3
i is 4
product of testval and i  is 20
i is 5
product of testval and i  is 5
i is 6
product of testval and i  is 6
i is 7
product of testval and i  is 0
i is 0
product of testval and i  is 0
i is 1
product of testval and i  is 0
i is 2
product of testval and i  is 4
i is 3
product of testval and i  is 3
i is 4
p

In [17]:
xTr = np.array([[1, 1 ,1],
 [1, 1, 0],
 [1, 0, 1],
 [1, 0, 0],
 [0, 1, 1],
 [0, 1, 0],
 [0 ,0, 1],
 [0, 0 ,0]])
yTr = np.array( [1, 0, 0, 1, 0, 1, 1, 0])

### feature,cut= 1,.5
print(xTr[:,1])
print(xTr[:,1] <= 0.5)
print(xTr[ xTr[:,1] <= 0.5])
print(yTr[ xTr[:,1] <= 0.5])

[1 1 0 0 1 1 0 0]
[False False  True  True False False  True  True]
[[1 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 0]]
[0 1 1 0]
