# Numpy related examples - collected by Satya

Try these examples, add your own problems , add comments to understand what is done at each cell level and download it for future practice. 

In [12]:
import numpy as np
X = np.array([[1,2,3],[4,5,6]])
print('X',X)
print('X.shape is',X.shape)
n,d = X.shape
print('n and d',n,d)

X [[1 2 3]
 [4 5 6]]
X.shape is (2, 3)
n and d 2 3


In [13]:
#
import numpy as np
Y = np.array([[1,2,3],[4,5,6]])
print('Y',Y)
print('Y.shape is',Y.shape)
n1,d1 = Y.shape
print('n1 and d1',n1,d1)

Y [[1 2 3]
 [4 5 6]]
Y.shape is (2, 3)
n1 and d1 2 3


In [14]:
Z = X*Y
print('X',X)
print('Y',Y)
print('Z',Z)

X [[1 2 3]
 [4 5 6]]
Y [[1 2 3]
 [4 5 6]]
Z [[ 1  4  9]
 [16 25 36]]


In [15]:

Z = X@Y
print('X',X)
print('Y',Y)
print('Z = X@Y',Z)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [16]:
'''
print('X.shape',X.shape)
print('Y.shape',Y.shape)
Z = X@Y
print('Z = X@Y',Z.shape)
'''

"\nprint('X.shape',X.shape)\nprint('Y.shape',Y.shape)\nZ = X@Y\nprint('Z = X@Y',Z.shape)\n"

In [17]:
print('X.shape',X.shape)
print('Y.shape',Y.shape)
Z = np.dot(X,Y)
print('Z = np.dot(X,Y)',Z.shape)


X.shape (2, 3)
Y.shape (2, 3)


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [18]:
print('X.shape',X.shape)

print('(Y.T).shape',(Y.T).shape)

Z = np.dot(X,Y.T)
print('X',X)
print('(Y.T)',(Y.T))
print('Z = np.dot(X,Y.T)',Z)

X.shape (2, 3)
(Y.T).shape (3, 2)
X [[1 2 3]
 [4 5 6]]
(Y.T) [[1 4]
 [2 5]
 [3 6]]
Z = np.dot(X,Y.T) [[14 32]
 [32 77]]


Squaring every value in the matrix

In [19]:
#How to square every value of a vector 
print('X',X)
print('X.shape',X.shape)

X [[1 2 3]
 [4 5 6]]
X.shape (2, 3)


In [20]:
print('X*X',X*X)

X*X [[ 1  4  9]
 [16 25 36]]


In [21]:
print('X**2',X**2)

X**2 [[ 1  4  9]
 [16 25 36]]


In [22]:
#print('X@X',X@X)

Column v/s Row totals

In [23]:
import numpy as np
marks = np.array([[41,62,63,64,45,66],[44,73,42,14,55,46],[74,27,55,44,64,43],[7,10,21,11,52,36],[31,42,34,54,55,86],[74,67,42,31,55,26],[41,25,53,84,35,66],[94,47,42,31,25,76]])
print('marks---------')
print(marks)
print('--------')
print('marks.shape is',marks.shape)
n2,d2 = marks.shape
print('tests and subjects',n2,d2)

marks---------
[[41 62 63 64 45 66]
 [44 73 42 14 55 46]
 [74 27 55 44 64 43]
 [ 7 10 21 11 52 36]
 [31 42 34 54 55 86]
 [74 67 42 31 55 26]
 [41 25 53 84 35 66]
 [94 47 42 31 25 76]]
--------
marks.shape is (8, 6)
tests and subjects 8 6


In [24]:
#Marks from test 1 
print('test ---')
print(marks[:1])
print(np.mean(marks[:1]))
print('------test ---')

test ---
[[41 62 63 64 45 66]]
56.833333333333336
------test ---


In [25]:
#totals  from each test
#row wise operation
print('test ---')

print(np.sum(marks,axis=1))
print('------test ---')

test ---
[341 274 307 137 302 295 304 315]
------test ---


In [26]:
#totals  from each subject
#column wise / dimension
print('test ---')

print(np.sum(marks,axis=0))
print('------test ---')

test ---
[406 353 352 333 386 445]
------test ---


In [27]:
# Add every subject some grace marks as given
grace = np.array([ 5,10,15,20,25,10])
print(grace.shape)
print(grace.ndim)

(6,)
1


In [28]:
print('marks shape',marks.shape)
print(marks)
print('-----')
print(grace)

marks shape (8, 6)
[[41 62 63 64 45 66]
 [44 73 42 14 55 46]
 [74 27 55 44 64 43]
 [ 7 10 21 11 52 36]
 [31 42 34 54 55 86]
 [74 67 42 31 55 26]
 [41 25 53 84 35 66]
 [94 47 42 31 25 76]]
-----
[ 5 10 15 20 25 10]


In [29]:
mgrace = marks+grace
print('marks with subject grace',mgrace)

marks with subject grace [[ 46  72  78  84  70  76]
 [ 49  83  57  34  80  56]
 [ 79  37  70  64  89  53]
 [ 12  20  36  31  77  46]
 [ 36  52  49  74  80  96]
 [ 79  77  57  51  80  36]
 [ 46  35  68 104  60  76]
 [ 99  57  57  51  50  86]]


In [30]:
# Add every subject some grace marks as given
#grace1 = np.array([ 5 10 15 20 25 10])
print(grace.shape)
print(grace.ndim)

(6,)
1


In [31]:
#---show this to all - Try using both versions of s1 and test
s1 = np.sum(marks**2,axis=1,keepdims = True)
#s1 = np.sum(marks**2,axis=1)
print(s1)
print(s1.shape)
print(s1.ndim)

[[19971]
 [14366]
 [17111]
 [ 4711]
 [17218]
 [16391]
 [17752]
 [20171]]
(8, 1)
2


In [32]:
print(marks+s1)

[[20012 20033 20034 20035 20016 20037]
 [14410 14439 14408 14380 14421 14412]
 [17185 17138 17166 17155 17175 17154]
 [ 4718  4721  4732  4722  4763  4747]
 [17249 17260 17252 17272 17273 17304]
 [16465 16458 16433 16422 16446 16417]
 [17793 17777 17805 17836 17787 17818]
 [20265 20218 20213 20202 20196 20247]]


In [33]:
s2 = np.sum(marks**2,axis=0,keepdims = True)
print(s2)
print(s2.shape)

[[26096 19089 16692 18243 19750 27821]]
(1, 6)


In [34]:
print(marks+s2)

[[26137 19151 16755 18307 19795 27887]
 [26140 19162 16734 18257 19805 27867]
 [26170 19116 16747 18287 19814 27864]
 [26103 19099 16713 18254 19802 27857]
 [26127 19131 16726 18297 19805 27907]
 [26170 19156 16734 18274 19805 27847]
 [26137 19114 16745 18327 19785 27887]
 [26190 19136 16734 18274 19775 27897]]


shape and reshape

In [35]:
npvec = np.array([1,2,3])

In [36]:
print(npvec.shape)

(3,)


In [37]:
colvec = npvec.reshape((3,1))
print(colvec)

[[1]
 [2]
 [3]]


In [38]:
'''
np.eye() creates an identity matrix
np.zeros() creates a matrix of all zeros
.arange() creates a vector of equally spaced values


'''

'\nnp.eye() creates an identity matrix\nnp.zeros() creates a matrix of all zeros\n.arange() creates a vector of equally spaced values\n\n\n'

In [39]:
import numpy as np
Xt = np.array([[1,2], [3,4]])
Yt = np.array([[5,6],[7,8]])
A = np.array([[1,2,3,4], [7,8,9,10]])
B = np.array([[4,5,6,7], [1,2,3,4]])

In [40]:
#print(A@B)

In [41]:
print(B.T)

[[4 1]
 [5 2]
 [6 3]
 [7 4]]


In [42]:
print(marks)

[[41 62 63 64 45 66]
 [44 73 42 14 55 46]
 [74 27 55 44 64 43]
 [ 7 10 21 11 52 36]
 [31 42 34 54 55 86]
 [74 67 42 31 55 26]
 [41 25 53 84 35 66]
 [94 47 42 31 25 76]]


In [43]:
print(marks)
print(np.sort(marks))

[[41 62 63 64 45 66]
 [44 73 42 14 55 46]
 [74 27 55 44 64 43]
 [ 7 10 21 11 52 36]
 [31 42 34 54 55 86]
 [74 67 42 31 55 26]
 [41 25 53 84 35 66]
 [94 47 42 31 25 76]]
[[41 45 62 63 64 66]
 [14 42 44 46 55 73]
 [27 43 44 55 64 74]
 [ 7 10 11 21 36 52]
 [31 34 42 54 55 86]
 [26 31 42 55 67 74]
 [25 35 41 53 66 84]
 [25 31 42 47 76 94]]


In [45]:
print(np.sort(marks,axis=0))

[[ 7 10 21 11 25 26]
 [31 25 34 14 35 36]
 [41 27 42 31 45 43]
 [41 42 42 31 52 46]
 [44 47 42 44 55 66]
 [74 62 53 54 55 66]
 [74 67 55 64 55 76]
 [94 73 63 84 64 86]]


In [34]:
print(np.argsort(marks,axis=0))

[[3 3 3 3 7 5]
 [4 6 4 1 6 3]
 [0 2 1 5 0 2]
 [6 4 5 7 3 1]
 [1 7 7 2 1 0]
 [2 0 6 4 4 6]
 [5 5 2 0 5 7]
 [7 1 0 6 2 4]]


In [35]:
indices = np.argsort(marks,axis=0)

In [36]:
print(indices)

[[3 3 3 3 7 5]
 [4 6 4 1 6 3]
 [0 2 1 5 0 2]
 [6 4 5 7 3 1]
 [1 7 7 2 1 0]
 [2 0 6 4 4 6]
 [5 5 2 0 5 7]
 [7 1 0 6 2 4]]


In [37]:
print(indices[:3,:])

[[3 3 3 3 7 5]
 [4 6 4 1 6 3]
 [0 2 1 5 0 2]]


In [38]:
print(indices[:,:1])

[[3]
 [4]
 [0]
 [6]
 [1]
 [2]
 [5]
 [7]]


Index reference between multiple arrays


In [11]:
#2/15
import numpy as np
xTr = np.array([[1,2,3,4], [7,8,9,10],[5,6,7,10],[11,12,13,14], [7,1,1,10],[5,6,7,10],[11,12,13,14], [7,1,1,10]])
print(xTr.shape)
yTr = np.array([1,-1,1,1,-1,1,-1,1])
#print(xTr[yTr==1])
#print(xTr[yTr==-1])
print(xTr)
idx = xTr[:,0]
print(idx)
idx_arg = xTr[:,0].argsort()
print(idx_arg)
print(xTr[idx_arg,0])
print(yTr[idx_arg])

(8, 4)
[[ 1  2  3  4]
 [ 7  8  9 10]
 [ 5  6  7 10]
 [11 12 13 14]
 [ 7  1  1 10]
 [ 5  6  7 10]
 [11 12 13 14]
 [ 7  1  1 10]]
[ 1  7  5 11  7  5 11  7]
[0 2 5 1 4 7 3 6]
[ 1  5  5  7  7  7 11 11]
[ 1  1  1 -1 -1  1  1 -1]


In [ ]:
print(training[0])

In [40]:
print(training[label==1])

[[ 1  2  3  4]
 [ 5  6  7 10]
 [11 12 13 14]]


In [43]:
print(training[label==-1])
testx = np.zeros(5)
print(testx)
testx[label==1] = 5
print(testx)

[[ 7  8  9 10]
 [ 7  1  1 10]]
[0. 0. 0. 0. 0.]
[5. 0. 5. 5. 0.]


In [ ]:
#mode([3,5,5,8,8,5]) = 5

In [44]:
x2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
print(x2[1:,:2])

[[4 5]
 [7 8]]


In [46]:
print(x2[:,0])

[1 4 7]


In [5]:
# 536 Specific

import numpy as np
x = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print(x)

print(x,x.shape)

print(x.reshape(-1,1))
print(x.reshape(6,2))
'''
print(x.reshape(-1,1).shape)

print(x.reshape(1,-1))


print(x.reshape(-1,2))
print(x.reshape(-1,2).shape)
print(x.reshape(6,2))
print(x.reshape(6,2).shape)
'''

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]] (4, 3)
[[11]
 [12]
 [13]
 [21]
 [22]
 [23]
 [31]
 [32]
 [33]
 [41]
 [42]
 [43]]
[[11 12]
 [13 21]
 [22 23]
 [31 32]
 [33 41]
 [42 43]]


'\nprint(x.reshape(-1,1).shape)\n\nprint(x.reshape(1,-1))\n\n\nprint(x.reshape(-1,2))\nprint(x.reshape(-1,2).shape)\nprint(x.reshape(6,2))\nprint(x.reshape(6,2).shape)\n'